defaults:
  - _self_
  - problem: tsp_constructive
  - override hydra/launcher: local
  - override hydra/output: local

problem_type: constructive

hydra:
  job:
    chdir: True

# LLM parameters
model: gpt-3.5-turbo  # LLM model (other options include gpt-4-1106-preview, gpt-3.5-turbo-16k-0613)
temperature: 1
suffix: GPT  # suffix for generated files (indicates LLM model)

# Main loop parameters
iteration: 3 # how many outer iterations to run
sample: 4 # number of code samples to generate per iteration
width: 10 # sampling width for an instance