defaults:
  - _self_
  - problem: tsp_constructive
  - override hydra/launcher: local
  - override hydra/output: local

problem_type: constructive

hydra:
  job:
    chdir: True

# LLM parameters
model: gpt-3.5-turbo  # LLM model (other options are gpt-4, gpt-4-0613, gpt-3.5-turbo-16k-0613)
temperature: 0.7
suffix: GPT  # suffix for generated files (indicates LLM model)

# Main loop parameters
iteration: 5 # how many outer iterations to run
sample: 2 # number of code samples to generate per iteration
width: 10 # sampling width for an instance
num_eval: 10 # number of evaluation instances to run