# @package _global_
hydra:
    launcher:
        cpus_per_task: 20
        timeout_min: 1600
        name: ${hydra.job.name}
        _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
        submitit_folder: ${hydra.sweep.dir}/.submitit/%j
